[package]
name = "apple-photos-export"
version = "1.2.0-snapshot"
edition = "2021"

[dependencies]
ascii_tree = "0.1.1"
chrono = "0.4.42"
clap = { version = "4.5.53", features = ["derive"] }
colored = "3.0.0"
plist = "1.8.0"
rand = "0.9.2"
rusqlite = { version = "0.37.0", features = ["bundled"] }
derive-new = "0.7.0"
walkdir = "2.5.0"
soft-canonicalize = "0.5"