name: Build and create draft release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  build:
    name: Build

    strategy:
      matrix:
        include:
          - host_os: macos-latest
            target: aarch64-apple-darwin

    uses: ./.github/workflows/_build.yml
    with:
      host_os: ${{ matrix.host_os }}
      target: ${{ matrix.target }}
      compiler_args: '--locked --release'
      upload_artifacts: true

  upload:
    name: Create draft release
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            # This is needed in order to generate a compliant tar ^archive name for `Justintime50/homebrew-releaser@v3`.
            # The above action requires the archives to have a very specific name that includes the target architecture.
            # The target uses a different naming schema than the standard rustc targets, though.
            tarball_name_target: darwin-arm64

    steps:
      - name: Get release version from tag
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Download compiled artifact
        uses: actions/download-artifact@v6
        with:
          # Name of the artifact uploaded by the common build workflow (_build.yml)
          name: 'target-${{ matrix.target }}'
          path: 'target'

      - name: Compress binary
        shell: bash
        run: |
          APP_NAME="apple-photos-export"
          
          VERSION=${{ env.VERSION }}
          NUMERICAL_VERSION=${VERSION#v}
          
          ZIP_FILE_NAME="${APP_NAME}-${NUMERICAL_VERSION}-${{ matrix.tarball_name_target }}.tar.gz"
          tar -czf $ZIP_FILE_NAME -C target/release/ ./$APP_NAME
          
          echo "ASSET=$ZIP_FILE_NAME" >> $GITHUB_ENV
          echo "NUMERICAL_VERSION=$NUMERICAL_VERSION" >> $GITHUB_ENV

      - name: Generate changelog
        id: changelog
        uses: requarks/changelog-action@v1.10.3
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
          useGitmojis: true

      - name: Create release and upload binaries
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.VERSION }}
          body: ${{ steps.changelog.outputs.changes }}
          draft: true
          tag_name: ${{ env.VERSION }}
          files: |
            ${{ env.ASSET }}